server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: backend
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  secret-arn: ${JWT_SECRET_ARN:}
DB_SECRET_ARN: ${DB_SECRET_ARN}
#logging:
#  level:
#    liquibase: DEBUG
#    liquibase.changelog: DEBUG
#    liquibase.executor: DEBUG

#  server.shutdown=graceful
#  spring.lifecycle.timeout-per-shutdown-phase=30s
